/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogSaleRouteImport } from './routes/log-sale'
import { Route as LogPurchaseRouteImport } from './routes/log-purchase'
import { Route as LogProcessingRouteImport } from './routes/log-processing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateNewPasswordRouteImport } from './routes/create-new-password'
import { Route as CollectorsRouteImport } from './routes/collectors'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BuyersRouteImport } from './routes/buyers'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as LogSaleSuccessRouteImport } from './routes/log-sale.success'
import { Route as LogPurchaseSuccessRouteImport } from './routes/log-purchase.success'
import { Route as CollectorsNewRouteImport } from './routes/collectors.new'
import { Route as CollectorsCollectorIdRouteImport } from './routes/collectors.$collectorId'
import { Route as BuyersNewRouteImport } from './routes/buyers.new'
import { Route as BuyersBuyerIdRouteImport } from './routes/buyers.$buyerId'
import { Route as BatchesProcessingRouteImport } from './routes/batches.processing'
import { Route as BatchesOutboundCreatedRouteImport } from './routes/batches.outbound-created'
import { Route as BatchesFlaggedRouteImport } from './routes/batches.flagged'
import { Route as BatchesBatchIdRouteImport } from './routes/batches.$batchId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogSaleRoute = LogSaleRouteImport.update({
  id: '/log-sale',
  path: '/log-sale',
  getParentRoute: () => rootRouteImport,
} as any)
const LogPurchaseRoute = LogPurchaseRouteImport.update({
  id: '/log-purchase',
  path: '/log-purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const LogProcessingRoute = LogProcessingRouteImport.update({
  id: '/log-processing',
  path: '/log-processing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateNewPasswordRoute = CreateNewPasswordRouteImport.update({
  id: '/create-new-password',
  path: '/create-new-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorsRoute = CollectorsRouteImport.update({
  id: '/collectors',
  path: '/collectors',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyersRoute = BuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const LogSaleSuccessRoute = LogSaleSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => LogSaleRoute,
} as any)
const LogPurchaseSuccessRoute = LogPurchaseSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => LogPurchaseRoute,
} as any)
const CollectorsNewRoute = CollectorsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CollectorsRoute,
} as any)
const CollectorsCollectorIdRoute = CollectorsCollectorIdRouteImport.update({
  id: '/$collectorId',
  path: '/$collectorId',
  getParentRoute: () => CollectorsRoute,
} as any)
const BuyersNewRoute = BuyersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BuyersRoute,
} as any)
const BuyersBuyerIdRoute = BuyersBuyerIdRouteImport.update({
  id: '/$buyerId',
  path: '/$buyerId',
  getParentRoute: () => BuyersRoute,
} as any)
const BatchesProcessingRoute = BatchesProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => BatchesRoute,
} as any)
const BatchesOutboundCreatedRoute = BatchesOutboundCreatedRouteImport.update({
  id: '/outbound-created',
  path: '/outbound-created',
  getParentRoute: () => BatchesRoute,
} as any)
const BatchesFlaggedRoute = BatchesFlaggedRouteImport.update({
  id: '/flagged',
  path: '/flagged',
  getParentRoute: () => BatchesRoute,
} as any)
const BatchesBatchIdRoute = BatchesBatchIdRouteImport.update({
  id: '/$batchId',
  path: '/$batchId',
  getParentRoute: () => BatchesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/alerts': typeof AlertsRoute
  '/batches': typeof BatchesRouteWithChildren
  '/buyers': typeof BuyersRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/collectors': typeof CollectorsRouteWithChildren
  '/create-new-password': typeof CreateNewPasswordRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/log-processing': typeof LogProcessingRoute
  '/log-purchase': typeof LogPurchaseRouteWithChildren
  '/log-sale': typeof LogSaleRouteWithChildren
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/batches/flagged': typeof BatchesFlaggedRoute
  '/batches/outbound-created': typeof BatchesOutboundCreatedRoute
  '/batches/processing': typeof BatchesProcessingRoute
  '/buyers/$buyerId': typeof BuyersBuyerIdRoute
  '/buyers/new': typeof BuyersNewRoute
  '/collectors/$collectorId': typeof CollectorsCollectorIdRoute
  '/collectors/new': typeof CollectorsNewRoute
  '/log-purchase/success': typeof LogPurchaseSuccessRoute
  '/log-sale/success': typeof LogSaleSuccessRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/alerts': typeof AlertsRoute
  '/batches': typeof BatchesRouteWithChildren
  '/buyers': typeof BuyersRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/collectors': typeof CollectorsRouteWithChildren
  '/create-new-password': typeof CreateNewPasswordRoute
  '/log-processing': typeof LogProcessingRoute
  '/log-purchase': typeof LogPurchaseRouteWithChildren
  '/log-sale': typeof LogSaleRouteWithChildren
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/batches/flagged': typeof BatchesFlaggedRoute
  '/batches/outbound-created': typeof BatchesOutboundCreatedRoute
  '/batches/processing': typeof BatchesProcessingRoute
  '/buyers/$buyerId': typeof BuyersBuyerIdRoute
  '/buyers/new': typeof BuyersNewRoute
  '/collectors/$collectorId': typeof CollectorsCollectorIdRoute
  '/collectors/new': typeof CollectorsNewRoute
  '/log-purchase/success': typeof LogPurchaseSuccessRoute
  '/log-sale/success': typeof LogSaleSuccessRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/alerts': typeof AlertsRoute
  '/batches': typeof BatchesRouteWithChildren
  '/buyers': typeof BuyersRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/collectors': typeof CollectorsRouteWithChildren
  '/create-new-password': typeof CreateNewPasswordRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/log-processing': typeof LogProcessingRoute
  '/log-purchase': typeof LogPurchaseRouteWithChildren
  '/log-sale': typeof LogSaleRouteWithChildren
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/batches/flagged': typeof BatchesFlaggedRoute
  '/batches/outbound-created': typeof BatchesOutboundCreatedRoute
  '/batches/processing': typeof BatchesProcessingRoute
  '/buyers/$buyerId': typeof BuyersBuyerIdRoute
  '/buyers/new': typeof BuyersNewRoute
  '/collectors/$collectorId': typeof CollectorsCollectorIdRoute
  '/collectors/new': typeof CollectorsNewRoute
  '/log-purchase/success': typeof LogPurchaseSuccessRoute
  '/log-sale/success': typeof LogSaleSuccessRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/alerts'
    | '/batches'
    | '/buyers'
    | '/checkout'
    | '/collectors'
    | '/create-new-password'
    | '/dashboard'
    | '/log-processing'
    | '/log-purchase'
    | '/log-sale'
    | '/login'
    | '/otp'
    | '/pricing'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/setup'
    | '/users'
    | '/batches/$batchId'
    | '/batches/flagged'
    | '/batches/outbound-created'
    | '/batches/processing'
    | '/buyers/$buyerId'
    | '/buyers/new'
    | '/collectors/$collectorId'
    | '/collectors/new'
    | '/log-purchase/success'
    | '/log-sale/success'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/alerts'
    | '/batches'
    | '/buyers'
    | '/checkout'
    | '/collectors'
    | '/create-new-password'
    | '/log-processing'
    | '/log-purchase'
    | '/log-sale'
    | '/login'
    | '/otp'
    | '/pricing'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/setup'
    | '/users'
    | '/batches/$batchId'
    | '/batches/flagged'
    | '/batches/outbound-created'
    | '/batches/processing'
    | '/buyers/$buyerId'
    | '/buyers/new'
    | '/collectors/$collectorId'
    | '/collectors/new'
    | '/log-purchase/success'
    | '/log-sale/success'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/alerts'
    | '/batches'
    | '/buyers'
    | '/checkout'
    | '/collectors'
    | '/create-new-password'
    | '/dashboard'
    | '/log-processing'
    | '/log-purchase'
    | '/log-sale'
    | '/login'
    | '/otp'
    | '/pricing'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/setup'
    | '/users'
    | '/batches/$batchId'
    | '/batches/flagged'
    | '/batches/outbound-created'
    | '/batches/processing'
    | '/buyers/$buyerId'
    | '/buyers/new'
    | '/collectors/$collectorId'
    | '/collectors/new'
    | '/log-purchase/success'
    | '/log-sale/success'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AlertsRoute: typeof AlertsRoute
  BatchesRoute: typeof BatchesRouteWithChildren
  BuyersRoute: typeof BuyersRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  CollectorsRoute: typeof CollectorsRouteWithChildren
  CreateNewPasswordRoute: typeof CreateNewPasswordRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LogProcessingRoute: typeof LogProcessingRoute
  LogPurchaseRoute: typeof LogPurchaseRouteWithChildren
  LogSaleRoute: typeof LogSaleRouteWithChildren
  LoginRoute: typeof LoginRoute
  OtpRoute: typeof OtpRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-sale': {
      id: '/log-sale'
      path: '/log-sale'
      fullPath: '/log-sale'
      preLoaderRoute: typeof LogSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-purchase': {
      id: '/log-purchase'
      path: '/log-purchase'
      fullPath: '/log-purchase'
      preLoaderRoute: typeof LogPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-processing': {
      id: '/log-processing'
      path: '/log-processing'
      fullPath: '/log-processing'
      preLoaderRoute: typeof LogProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-new-password': {
      id: '/create-new-password'
      path: '/create-new-password'
      fullPath: '/create-new-password'
      preLoaderRoute: typeof CreateNewPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collectors': {
      id: '/collectors'
      path: '/collectors'
      fullPath: '/collectors'
      preLoaderRoute: typeof CollectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyers': {
      id: '/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof BuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/log-sale/success': {
      id: '/log-sale/success'
      path: '/success'
      fullPath: '/log-sale/success'
      preLoaderRoute: typeof LogSaleSuccessRouteImport
      parentRoute: typeof LogSaleRoute
    }
    '/log-purchase/success': {
      id: '/log-purchase/success'
      path: '/success'
      fullPath: '/log-purchase/success'
      preLoaderRoute: typeof LogPurchaseSuccessRouteImport
      parentRoute: typeof LogPurchaseRoute
    }
    '/collectors/new': {
      id: '/collectors/new'
      path: '/new'
      fullPath: '/collectors/new'
      preLoaderRoute: typeof CollectorsNewRouteImport
      parentRoute: typeof CollectorsRoute
    }
    '/collectors/$collectorId': {
      id: '/collectors/$collectorId'
      path: '/$collectorId'
      fullPath: '/collectors/$collectorId'
      preLoaderRoute: typeof CollectorsCollectorIdRouteImport
      parentRoute: typeof CollectorsRoute
    }
    '/buyers/new': {
      id: '/buyers/new'
      path: '/new'
      fullPath: '/buyers/new'
      preLoaderRoute: typeof BuyersNewRouteImport
      parentRoute: typeof BuyersRoute
    }
    '/buyers/$buyerId': {
      id: '/buyers/$buyerId'
      path: '/$buyerId'
      fullPath: '/buyers/$buyerId'
      preLoaderRoute: typeof BuyersBuyerIdRouteImport
      parentRoute: typeof BuyersRoute
    }
    '/batches/processing': {
      id: '/batches/processing'
      path: '/processing'
      fullPath: '/batches/processing'
      preLoaderRoute: typeof BatchesProcessingRouteImport
      parentRoute: typeof BatchesRoute
    }
    '/batches/outbound-created': {
      id: '/batches/outbound-created'
      path: '/outbound-created'
      fullPath: '/batches/outbound-created'
      preLoaderRoute: typeof BatchesOutboundCreatedRouteImport
      parentRoute: typeof BatchesRoute
    }
    '/batches/flagged': {
      id: '/batches/flagged'
      path: '/flagged'
      fullPath: '/batches/flagged'
      preLoaderRoute: typeof BatchesFlaggedRouteImport
      parentRoute: typeof BatchesRoute
    }
    '/batches/$batchId': {
      id: '/batches/$batchId'
      path: '/$batchId'
      fullPath: '/batches/$batchId'
      preLoaderRoute: typeof BatchesBatchIdRouteImport
      parentRoute: typeof BatchesRoute
    }
  }
}

interface BatchesRouteChildren {
  BatchesBatchIdRoute: typeof BatchesBatchIdRoute
  BatchesFlaggedRoute: typeof BatchesFlaggedRoute
  BatchesOutboundCreatedRoute: typeof BatchesOutboundCreatedRoute
  BatchesProcessingRoute: typeof BatchesProcessingRoute
}

const BatchesRouteChildren: BatchesRouteChildren = {
  BatchesBatchIdRoute: BatchesBatchIdRoute,
  BatchesFlaggedRoute: BatchesFlaggedRoute,
  BatchesOutboundCreatedRoute: BatchesOutboundCreatedRoute,
  BatchesProcessingRoute: BatchesProcessingRoute,
}

const BatchesRouteWithChildren =
  BatchesRoute._addFileChildren(BatchesRouteChildren)

interface BuyersRouteChildren {
  BuyersBuyerIdRoute: typeof BuyersBuyerIdRoute
  BuyersNewRoute: typeof BuyersNewRoute
}

const BuyersRouteChildren: BuyersRouteChildren = {
  BuyersBuyerIdRoute: BuyersBuyerIdRoute,
  BuyersNewRoute: BuyersNewRoute,
}

const BuyersRouteWithChildren =
  BuyersRoute._addFileChildren(BuyersRouteChildren)

interface CollectorsRouteChildren {
  CollectorsCollectorIdRoute: typeof CollectorsCollectorIdRoute
  CollectorsNewRoute: typeof CollectorsNewRoute
}

const CollectorsRouteChildren: CollectorsRouteChildren = {
  CollectorsCollectorIdRoute: CollectorsCollectorIdRoute,
  CollectorsNewRoute: CollectorsNewRoute,
}

const CollectorsRouteWithChildren = CollectorsRoute._addFileChildren(
  CollectorsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface LogPurchaseRouteChildren {
  LogPurchaseSuccessRoute: typeof LogPurchaseSuccessRoute
}

const LogPurchaseRouteChildren: LogPurchaseRouteChildren = {
  LogPurchaseSuccessRoute: LogPurchaseSuccessRoute,
}

const LogPurchaseRouteWithChildren = LogPurchaseRoute._addFileChildren(
  LogPurchaseRouteChildren,
)

interface LogSaleRouteChildren {
  LogSaleSuccessRoute: typeof LogSaleSuccessRoute
}

const LogSaleRouteChildren: LogSaleRouteChildren = {
  LogSaleSuccessRoute: LogSaleSuccessRoute,
}

const LogSaleRouteWithChildren =
  LogSaleRoute._addFileChildren(LogSaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AlertsRoute: AlertsRoute,
  BatchesRoute: BatchesRouteWithChildren,
  BuyersRoute: BuyersRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  CollectorsRoute: CollectorsRouteWithChildren,
  CreateNewPasswordRoute: CreateNewPasswordRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LogProcessingRoute: LogProcessingRoute,
  LogPurchaseRoute: LogPurchaseRouteWithChildren,
  LogSaleRoute: LogSaleRouteWithChildren,
  LoginRoute: LoginRoute,
  OtpRoute: OtpRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
